apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dtsu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0059-tenant/ci10t-776-0059-app/devfile-sample-dtsu@sha256:0d3244d7b02122a74903066bf69fcfb31920e85278b559288a03830bdca002c8
        name: my-nodejs
        resources: {}
status: {}
